### ISSUE TITLE
 does not work anymore

### ISSUE THREAD

**Issue by R4PH4** [plylrnsdy/vscode-run-as#4]
Hello for some time run as has not worked, I can't explain it to myself,

What do you need as information to debug me?

**Comment by plylrnsdy** [comment]
It maybe help me to reproduce the problem if you provide these information:
1. OS, like `Windows 10 2004 x64`
2. VSCode version, like `VSCode 1.50.1(user setup)`
3. Open a folder or a workspace in VSCode?
4. File path which run-as did not work on
5. run-as configuration

By the way, it is welcome to make a pull request to the repo if you fix it by yourself.

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/97870178-e85da480-1d12-11eb-9fa0-367945c57713.png)

**Comment by R4PH4** [comment]
I want to open a file with the native windows application

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/97870968-0f68a600-1d14-11eb-9b84-11f52b1d82a6.png)

**Comment by R4PH4** [comment]
![image](https://user-images.githubusercontent.com/58464986/97871149-535bab00-1d14-11eb-8c3f-4f6a500d9301.png)

**Comment by plylrnsdy** [comment]
Are you using VSCode Remote SSH in Windows to connect a Linux environment?

**Comment by R4PH4** [comment]
no

**Comment by plylrnsdy** [comment]
Is it a terminal in WSL?

**Comment by R4PH4** [comment]
normally yes, it worked well before

**Comment by plylrnsdy** [comment]
Did you change your VSCode integrated terminal like this: `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"` ?
I think that run-as can not work well with WSL's terminal.

**Comment by plylrnsdy** [comment]
I can fix this by running a PowerShell to open the file with native Windows application, and you can use `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"` as the same time.

**Comment by R4PH4** [comment]
thank you !
